{
    'name': 'Saas Sysadmin AWS Route53',
    'summary': 'This module can be used by other SaaS modules when DNS needed',
    'category': 'SaaS',
    'images': [],
    'version': '18.0.1.0.0',
    'author': 'IT-Projects LLC, Cheick Oumar Tidiane Traore',
    'support': 'apps@itexperts4africa.com',
    'website': 'https://www.itexperts4africa.com',
    'license': 'LGPL-3',
    'depends': ['saas_sysadmin', 'saas_sysadmin_aws'],
    'external_dependencies': {'python': ['boto'], 'bin': []},
    'data': ['views/saas_sysadmin_aws_route53.xml'],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'sequence': 10,
}
