{
    'name': 'Demo datatabases',
    'summary': 'All you need to create demos for your applications in odoo apps store',
    'category': 'SaaS',
    'images': [],
    'version': '18.0.1.0.0',
    'author': 'IT-Projects LLC, Cheick Oumar Tidiane Traore',
    'website': 'https://www.itexperts4africa.com',
    'license': 'GPL-3',
    'depends': ['saas_portal', 'website_sale', 'saas_portal_sale_online', 'portal'],
    'external_dependencies': {'python': ['requests'], 'bin': []},
    'data': ['security/ir.model.access.csv', 'security/saas_portal_demo.xml', 'views/templates.xml', 'views/saas_portal_demo.xml', 'views/product.xml', 'views/saas_portal_demo_templates.xml', 'data/product.xml', 'data/ir_cron.xml', 'data/mail_template.xml', 'data/ir_actions.xml'],
    'qweb': [],
    'demo': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'installable': True,
    'auto_install': False,
    'application': False,
    'sequence': 10,
}
