{
    'name': 'Local IP for OAuth requests',
    'summary': 'Allows to check access_token by requests in local network',
    'category': 'Extra Tools',
    'images': [],
    'version': '18.0.1.0.0',
    'author': 'IT-Projects LLC, Cheick Oumar Tidiane Traore',
    'support': 'apps@itexperts4africa.com',
    'website': 'https://www.itexperts4africa.com',
    'license': 'LGPL-3',
    'depends': ['auth_oauth'],
    'external_dependencies': {'python': [], 'bin': []},
    'data': ['views.xml'],
    'qweb': [],
    'demo': [],
    'post_load': None,
    'pre_init_hook': None,
    'post_init_hook': None,
    'installable': True,
    'auto_install': False,
    'application': False,
    'sequence': 10,
}
