from . import res_config
from . import saas_portal
from . import saas_portal_plan
from . import ir_config_parameter
from . import res_users
from . import ir_actions_act_window
from . import ir_ui_view
from . import saas_portal_optimization
from . import saas_portal_sql_optimization
