[options]
# ---------- Authentification ----------
admin_passwd = admin

# ---------- Base de données (conteneur) ----------
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo
db_filter = .*

# ---------- Modules ----------
addons_path = /mnt/extra-addons,
              /usr/lib/python3/dist-packages/odoo/addons

# ---------- Fichiers & logs ----------
data_dir = /var/lib/odoo
logfile = /var/log/odoo/odoo.log
log_level = info

# ---------- Serveur ----------
xmlrpc_port = 8069
longpolling_port = 8072
workers = 3
max_cron_threads = 2

# ---------- Performance & limites ----------
limit_time_cpu = 120
limit_time_real = 240
limit_memory_soft = 1342177280   # 1,25 Go
limit_memory_hard = 1610612736   # 1,5 Go

# ---------- Divers ----------
without_demo = True
proxy_mode = False

