{
    'name': 'Saas Sysadmin Mailgun',
    'summary': 'This module configurates new databases for clients such as their users can send and receive mails',
    'category': 'SaaS',
    'images': [],
    'version': '18.0.1.0.0',
    'author': 'IT-Projects LLC, Cheick Oumar Tidiane Traore',
    'support': 'apps@itexperts4africa.com',
    'website': 'https://www.itexperts4africa.com',
    'license': 'LGPL-3',
    'depends': ['base'],
    'external_dependencies': {'python': ['boto'], 'bin': []},
    'data': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'sequence': 10,
}
